INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/thrift/TApplicationException.h \
    $$PWD/thrift/TBase.h \
    $$PWD/thrift/TConfiguration.h \
    $$PWD/thrift/TDispatchProcessor.h \
    $$PWD/thrift/TLogging.h \
    $$PWD/thrift/TNonCopyable.h \
    $$PWD/thrift/TOutput.h \
    $$PWD/thrift/TProcessor.h \
    $$PWD/thrift/TToString.h \
    $$PWD/thrift/Thrift.h \
    $$PWD/thrift/async/TAsyncBufferProcessor.h \
    $$PWD/thrift/async/TAsyncChannel.h \
    $$PWD/thrift/async/TAsyncDispatchProcessor.h \
    $$PWD/thrift/async/TAsyncProcessor.h \
    $$PWD/thrift/async/TAsyncProtocolProcessor.h \
    $$PWD/thrift/async/TConcurrentClientSyncInfo.h \
    $$PWD/thrift/async/TEvhttpClientChannel.h \
    $$PWD/thrift/async/TEvhttpServer.h \
    $$PWD/thrift/concurrency/Exception.h \
    $$PWD/thrift/concurrency/FunctionRunner.h \
    $$PWD/thrift/concurrency/Monitor.h \
    $$PWD/thrift/concurrency/Mutex.h \
    $$PWD/thrift/concurrency/Thread.h \
    $$PWD/thrift/concurrency/ThreadFactory.h \
    $$PWD/thrift/concurrency/ThreadManager.h \
    $$PWD/thrift/concurrency/TimerManager.h \
    $$PWD/thrift/processor/PeekProcessor.h \
    $$PWD/thrift/processor/StatsProcessor.h \
    $$PWD/thrift/processor/TMultiplexedProcessor.h \
    $$PWD/thrift/protocol/TBase64Utils.h \
    $$PWD/thrift/protocol/TBinaryProtocol.h \
    $$PWD/thrift/protocol/TBinaryProtocol.tcc \
    $$PWD/thrift/protocol/TCompactProtocol.h \
    $$PWD/thrift/protocol/TCompactProtocol.tcc \
    $$PWD/thrift/protocol/TDebugProtocol.h \
    $$PWD/thrift/protocol/TEnum.h \
    $$PWD/thrift/protocol/THeaderProtocol.h \
    $$PWD/thrift/protocol/TJSONProtocol.h \
    $$PWD/thrift/protocol/TList.h \
    $$PWD/thrift/protocol/TMap.h \
    $$PWD/thrift/protocol/TMultiplexedProtocol.h \
    $$PWD/thrift/protocol/TProtocol.h \
    $$PWD/thrift/protocol/TProtocolDecorator.h \
    $$PWD/thrift/protocol/TProtocolException.h \
    $$PWD/thrift/protocol/TProtocolTap.h \
    $$PWD/thrift/protocol/TProtocolTypes.h \
    $$PWD/thrift/protocol/TSet.h \
    $$PWD/thrift/protocol/TVirtualProtocol.h \
    $$PWD/thrift/qt/TQIODeviceTransport.h \
    $$PWD/thrift/qt/TQTcpServer.h \
    $$PWD/thrift/server/TConnectedClient.h \
    $$PWD/thrift/server/TNonblockingServer.h \
    $$PWD/thrift/server/TServer.h \
    $$PWD/thrift/server/TServerFramework.h \
    $$PWD/thrift/server/TSimpleServer.h \
    $$PWD/thrift/server/TThreadPoolServer.h \
    $$PWD/thrift/server/TThreadedServer.h \
    $$PWD/thrift/thrift-config.h \
    $$PWD/thrift/thrift_export.h \
    $$PWD/thrift/transport/PlatformSocket.h \
    $$PWD/thrift/transport/SocketCommon.h \
    $$PWD/thrift/transport/TBufferTransports.h \
    $$PWD/thrift/transport/TFDTransport.h \
    $$PWD/thrift/transport/TFileTransport.h \
    $$PWD/thrift/transport/THeaderTransport.h \
    $$PWD/thrift/transport/THttpClient.h \
    $$PWD/thrift/transport/THttpServer.h \
    $$PWD/thrift/transport/THttpTransport.h \
    $$PWD/thrift/transport/TNonblockingSSLServerSocket.h \
    $$PWD/thrift/transport/TNonblockingServerSocket.h \
    $$PWD/thrift/transport/TNonblockingServerTransport.h \
    $$PWD/thrift/transport/TPipe.h \
    $$PWD/thrift/transport/TPipeServer.h \
    $$PWD/thrift/transport/TSSLServerSocket.h \
    $$PWD/thrift/transport/TSSLSocket.h \
    $$PWD/thrift/transport/TServerSocket.h \
    $$PWD/thrift/transport/TServerTransport.h \
    $$PWD/thrift/transport/TShortReadTransport.h \
    $$PWD/thrift/transport/TSimpleFileTransport.h \
    $$PWD/thrift/transport/TSocket.h \
    $$PWD/thrift/transport/TSocketPool.h \
    $$PWD/thrift/transport/TSocketUtils.h \
    $$PWD/thrift/transport/TTransport.h \
    $$PWD/thrift/transport/TTransportException.h \
    $$PWD/thrift/transport/TTransportUtils.h \
    $$PWD/thrift/transport/TVirtualTransport.h \
    $$PWD/thrift/transport/TWebSocketServer.h \
    $$PWD/thrift/transport/TZlibTransport.h \
    $$PWD/thrift/windows/GetTimeOfDay.h \
    $$PWD/thrift/windows/Operators.h \
    $$PWD/thrift/windows/OverlappedSubmissionThread.h \
    $$PWD/thrift/windows/SocketPair.h \
    $$PWD/thrift/windows/Sync.h \
    $$PWD/thrift/windows/TWinsockSingleton.h \
    $$PWD/thrift/windows/WinFcntl.h \
    $$PWD/thrift/windows/config.h

SOURCES += \
    $$PWD/thrift/TApplicationException.cpp \
    $$PWD/thrift/TOutput.cpp \
    $$PWD/thrift/VirtualProfiling.cpp \
    $$PWD/thrift/async/TAsyncChannel.cpp \
    $$PWD/thrift/async/TAsyncProtocolProcessor.cpp \
    $$PWD/thrift/async/TConcurrentClientSyncInfo.cpp \
    $$PWD/thrift/async/TEvhttpClientChannel.cpp \
    $$PWD/thrift/async/TEvhttpServer.cpp \
    $$PWD/thrift/concurrency/Monitor.cpp \
    $$PWD/thrift/concurrency/Mutex.cpp \
    $$PWD/thrift/concurrency/Thread.cpp \
    $$PWD/thrift/concurrency/ThreadFactory.cpp \
    $$PWD/thrift/concurrency/ThreadManager.cpp \
    $$PWD/thrift/concurrency/TimerManager.cpp \
    $$PWD/thrift/processor/PeekProcessor.cpp \
    $$PWD/thrift/protocol/TBase64Utils.cpp \
    $$PWD/thrift/protocol/TDebugProtocol.cpp \
    $$PWD/thrift/protocol/THeaderProtocol.cpp \
    $$PWD/thrift/protocol/TJSONProtocol.cpp \
    $$PWD/thrift/protocol/TMultiplexedProtocol.cpp \
    $$PWD/thrift/protocol/TProtocol.cpp \
    $$PWD/thrift/qt/TQIODeviceTransport.cpp \
    $$PWD/thrift/qt/TQTcpServer.cpp \
    $$PWD/thrift/server/TConnectedClient.cpp \
    $$PWD/thrift/server/TNonblockingServer.cpp \
    $$PWD/thrift/server/TServer.cpp \
    $$PWD/thrift/server/TServerFramework.cpp \
    $$PWD/thrift/server/TSimpleServer.cpp \
    $$PWD/thrift/server/TThreadPoolServer.cpp \
    $$PWD/thrift/server/TThreadedServer.cpp \
    $$PWD/thrift/transport/SocketCommon.cpp \
    $$PWD/thrift/transport/TBufferTransports.cpp \
    $$PWD/thrift/transport/TFDTransport.cpp \
    $$PWD/thrift/transport/TFileTransport.cpp \
    $$PWD/thrift/transport/THeaderTransport.cpp \
    $$PWD/thrift/transport/THttpClient.cpp \
    $$PWD/thrift/transport/THttpServer.cpp \
    $$PWD/thrift/transport/THttpTransport.cpp \
    $$PWD/thrift/transport/TNonblockingSSLServerSocket.cpp \
    $$PWD/thrift/transport/TNonblockingServerSocket.cpp \
    $$PWD/thrift/transport/TPipe.cpp \
    $$PWD/thrift/transport/TPipeServer.cpp \
    $$PWD/thrift/transport/TSSLServerSocket.cpp \
    $$PWD/thrift/transport/TSSLSocket.cpp \
    $$PWD/thrift/transport/TServerSocket.cpp \
    $$PWD/thrift/transport/TSimpleFileTransport.cpp \
    $$PWD/thrift/transport/TSocket.cpp \
    $$PWD/thrift/transport/TSocketPool.cpp \
    $$PWD/thrift/transport/TTransportException.cpp \
    $$PWD/thrift/transport/TTransportUtils.cpp \
    $$PWD/thrift/transport/TWebSocketServer.cpp \
    $$PWD/thrift/transport/TZlibTransport.cpp \
    $$PWD/thrift/windows/GetTimeOfDay.cpp \
    $$PWD/thrift/windows/OverlappedSubmissionThread.cpp \
    $$PWD/thrift/windows/SocketPair.cpp \
    $$PWD/thrift/windows/TWinsockSingleton.cpp \
    $$PWD/thrift/windows/WinFcntl.cpp
